[build]
  command = "pnpm run build"
  publish = "dist/public"

[[redirects]]
  from = "/*"
  to = "/shell.html"
  status = 200

[context.production]
  command = "pnpm run build"
  publish = "dist/public"
